import img from "../src/Components/assets/caravan1.png";

export const campcar = {
  maindata: [
    {
      id: 1,
      car: {
        photo: `${img}`,
        name: "르벤투스S+",
        cost: "90,200,000",
        type: "르노마스터",
        license: "1종 보통",
        people: "4인",
        date: "22년 03월",
        company: "다온티앤티",
        location: "수도권",
      },
    },
    {
      id: 2,
      car: {
        photo: `${img}`,
        name: "르벤투스680S",
        cost: "93,700,000",
        type: "르노마스터",
        license: "1종 보통",
        people: "4인",
        date: "22년 03월",
        company: "다온티앤티",
        location: "수도권",
      },
    },
    {
      id: 3,
      car: {
        photo: `${img}`,
        name: "르벤투스680",
        cost: "93,700,000",
        type: "르노마스터",
        license: "1종 보통",
        people: "5인",
        date: "22년 03월",
        company: "다온티앤티",
        location: "수도권",
      },
    },
    {
      id: 4,
      car: {
        photo: `${img}`,
        name: "르벤투스 차박S",
        cost: "66,100,000",
        type: "르노마스터",
        license: "1종 보통",
        people: "4인",
        date: "22년 03월",
        company: "다온티앤티",
        location: "수도권",
      },
    },
    {
      id: 5,
      car: {
        photo: `${img}`,
        name: "포스650",
        cost: "85,300,000",
        type: "포터",
        license: "2종 보통",
        people: "6인",
        date: "22년 03월",
        company: "다온티앤티",
        location: "수도권",
      },
    },
    {
      id: 6,
      car: {
        photo: `${img}`,
        name: "포스560",
        cost: "93,700,000",
        type: "포터",
        license: "2종 보통",
        people: "6인",
        date: "22년 03월",
        company: "다온티앤티",
        location: "수도권",
      },
    },
    {
      id: 7,
      car: {
        photo: `${img}`,
        name: "올카",
        cost: "62,600,000",
        type: "포터",
        license: "2종 보통",
        people: "3인",
        date: "22년 03월",
        company: "다온티앤티",
        location: "수도권",
      },
    },
    {
      id: 8,
      car: {
        photo: `${img}`,
        name: "DS9eR+a",
        cost: "77,900,000",
        type: "봉고",
        license: "2종 보통",
        people: "6인",
        date: "22년 03월",
        company: "제일모빌",
        location: "수도권",
      },
    },
    {
      id: 9,
      car: {
        photo: `${img}`,
        name: "DS9eU+a",
        cost: "75,200,000",
        type: "봉고",
        license: "2종 보통",
        people: "5인",
        date: "22년 03월",
        company: "제일모빌",
        location: "수도권",
      },
    },
    {
      id: 10,
      car: {
        photo: `${img}`,
        name: "ACIER 790R",
        cost: "122,800,000",
        type: "이베코 뉴데일리",
        license: "1종 보통",
        people: "6인",
        date: "22년 03월",
        company: "제일모빌",
        location: "수도권",
      },
    },
    {
      id: 12,
      car: {
        photo: `${img}`,
        name: "ACIER 900 Deluxe",
        cost: "142,800,000",
        type: "이베코 뉴데일리",
        license: "1종 보통",
        people: "6인",
        date: "22년 03월",
        company: "제일모빌",
        location: "수도권",
      },
    },
    {
      id: 16,
      car: {
        photo: `${img}`,
        name: "ST-7",
        cost: "89,000,000",
        type: "봉고",
        license: "2종 보통",
        people: "5인",
        date: "22년 03월",
        company: "스타모빌",
        location: " 경상권",
      },
    },
    {
      id: 20,
      car: {
        photo: `${img}`,
        name: "트레블라인 660",
        cost: "76,000,000",
        type: "르노마스터",
        license: "1종 보통",
        people: "3인",
        date: "22년 03월",
        company: "영남캠핑카",
        location: "경상권",
      },
    },
    {
      id: 21,
      car: {
        photo: `${img}`,
        name: "트레블라인 550",
        cost: "60,000,000",
        type: "르노마스터",
        license: "1종 보통",
        people: "3인",
        date: "22년 03월",
        company: "영남캠핑카",
        location: "경상권",
      },
    },
    {
      id: 22,
      car: {
        photo: `${img}`,
        name: "트레블라인 650,",
        cost: "68,900,000",
        type: "봉고",
        license: "2종 보통",
        people: "5인",
        date: "22년 03월",
        company: " 영남캠핑카",
        location: "경상권",
      },
    },
    {
      id: 23,
      car: {
        photo: `${img}`,
        name: "트레블라인 350",
        cost: "59,900,000",
        type: "봉고",
        license: "2종 보통",
        people: "5인",
        date: "22년 03월",
        company: "영남캠핑카",
        location: "경상권",
      },
    },
    {
      id: 24,
      car: {
        photo: `${img}`,
        name: "트레블라인 250,",
        cost: "49,000,000",
        type: "포터",
        license: "2종 보통",
        people: "3인",
        date: "22년 03월",
        company: "영남캠핑카",
        location: "경상권",
      },
    },
    {
      id: 25,
      car: {
        photo: `${img}`,
        name: "트레블라인 220",
        cost: "39,000,000",
        type: "포터",
        license: "2종 보통",
        people: "3인",
        date: "22년 03월",
        company: "영남캠핑카",
        location: "경상권",
      },
    },
    {
      id: 31,
      car: {
        photo: " //",
        name: "HWC560DL",
        cost: "61,000,000",
        type: "포터",
        license: "2종 보통",
        people: " 6인",
        date: "22년 03월",
        company: "한울캠핑카",
        location: "경상권",
      },
    },
    {
      id: 32,
      car: {
        photo: `${img}`,
        name: "HWC620DL",
        cost: "76,000,000",
        type: "봉고",
        license: "2종 보통",
        people: "5인",
        date: "22년 03월",
        company: "한울캠핑카",
        location: "경상권",
      },
    },
    {
      id: 33,
      car: {
        photo: `${img}`,
        name: "HWC680L",
        cost: "75,000,000",
        type: "르노마스터",
        license: "1종 보통",
        people: "3인",
        date: "22년 03월",
        company: "한울캠핑카",
        location: "경상권",
      },
    },
    {
      id: 34,
      car: {
        photo: `${img}`,
        name: "HWC680DL",
        cost: "77,000,000",
        type: "르노마스터",
        license: "1종 보통",
        people: "5인",
        date: "22년 03월",
        company: "한울캠핑카",
        location: "경상권",
      },
    },
    {
      id: 35,
      car: {
        photo: `${img}`,
        name: "HWC560F",
        cost: "64,000,000",
        type: "포터",
        license: " 2종 보통",
        people: "6인",
        date: "22년 03월",
        company: "한울캠핑카",
        location: "경상권",
      },
    },
    {
      id: 36,
      car: {
        photo: `${img}`,
        name: "헤르메스550",
        cost: "64,000,000",
        type: "봉고",
        license: "2종 보통",
        people: "5인",
        date: "22년 03월",
        company: "훼미리캠핑카",
        location: "경상권",
      },
    },
    {
      id: 37,
      car: {
        photo: " //",
        name: "헤르메스650",
        cost: "77,000,000",
        type: "봉고",
        license: "2종 보통",
        people: "5인",
        date: "22년 03월",
        company: "훼미리캠핑카",
        location: "경상권",
      },
    },
    {
      id: 38,
      car: {
        photo: `${img}`,
        name: "V-70",
        cost: "64,900,000",
        type: "칸",
        license: " 2종 보통",
        people: "5인",
        date: "22년 03월",
        company: "에이스캠퍼",
        location: "충청권",
      },
    },
    {
      id: 39,
      car: {
        photo: `${img}`,
        name: "HASSLA",
        cost: "74,900,000",
        type: "봉고",
        license: "2종 보통",
        people: "5인",
        date: "22년 03월",
        company: "에이스캠퍼",
        location: "충청권",
      },
    },
    {
      id: 40,
      car: {
        photo: `${img}`,
        name: "오버랜드",
        cost: "89,800,000",
        type: "르노마스터",
        license: " 1종 보통",
        people: "4인",
        date: "22년 03월",
        company: "월든모빌",
        location: "수도권",
      },
    },
    {
      id: 45,
      car: {
        photo: `${img}`,
        name: "다비드 럭셔리",
        cost: "66,093,900",
        type: "르노마스터",
        license: "1종 보통",
        people: "3인",
        date: "22년 03월",
        company: " 위드원모터스",
        location: " 수도권",
      },
    },
    {
      id: 46,
      car: {
        photo: `${img}`,
        name: "다비드 스페셜",
        cost: "68,223,900",
        type: "르노마스터",
        license: " 1종 보통",
        people: "3인",
        date: "22년 03월",
        company: "위드원모터스",
        location: "수도권",
      },
    },
    {
      id: 47,
      car: {
        photo: `${img}`,
        name: "다비드 패밀리",
        cost: "69,501,900",
        type: "르노마스터",
        license: "1종 보통",
        people: "4인",
        date: "22년 03월",
        company: "위드원모터스",
        location: "수도권",
      },
    },
    {
      id: 48,
      car: {
        photo: `${img}`,
        name: "다비드 베이직",
        cost: "60,342,900",
        type: "르노마스터",
        license: "1종 보통",
        people: "3인",
        date: "22년 03월",
        company: "위드원모터스",
        location: "수도권",
      },
    },
    {
      id: 49,
      car: {
        photo: `${img}`,
        name: "WD5-410",
        cost: "69,225,000",
        type: "포터",
        license: "2종 보통",
        people: "5인",
        date: "22년 03월",
        company: "위드원모터스",
        location: "수도권",
      },
    },
    {
      id: 50,
      car: {
        photo: `${img}`,
        name: "WD-390",
        cost: "67,521,000",
        type: " 포터",
        license: "2종 보통",
        people: "3인",
        date: "22년 03월",
        company: "위드원모터스",
        location: "수도권",
      },
    },
    {
      id: 51,
      car: {
        photo: `${img}`,
        name: "WD-330",
        cost: "61,770,000",
        type: "포터",
        license: "2종 보통",
        people: "3인",
        date: "22년 03월",
        company: "위드원모터스",
        location: "수도권",
      },
    },
    {
      id: 52,
      car: {
        photo: `${img}`,
        name: "MARLIN",
        cost: "49,860,000",
        type: "포터",
        license: "2종 보통",
        people: " 3인",
        date: "22년 03월",
        company: "위드원모터스",
        location: "수도권",
      },
    },
    {
      id: 53,
      car: {
        photo: `${img}`,
        name: "테라-G6",
        cost: "68,000,000",
        type: "봉고",
        license: "2종 보통",
        people: "5인",
        date: "22년 03월",
        company: "미스터캠퍼",
        location: "수도권",
      },
    },
    {
      id: 54,
      car: {
        photo: `${img}`,
        name: "테라-X6",
        cost: "68,000,000",
        type: "봉고",
        license: "2종 보통",
        people: "5인",
        date: "22년 03월",
        company: "미스터캠퍼",
        location: "수도권",
      },
    },
    {
      id: 55,
      car: {
        photo: `${img}`,
        name: "테라-X7",
        cost: "85,000,000",
        type: "봉고",
        license: "2종 보통",
        people: "5인",
        date: "22년 03월",
        company: "미스터캠퍼",
        location: "수도권",
      },
    },
    {
      id: 90,
      car: {
        photo: `${img}`,
        name: "프라임640",
        cost: "79,900,000",
        type: "포터",
        license: "2종 보통",
        people: "5인",
        date: "22년 03월",
        company: "드림캠핑카",
        location: "경상권",
      },
    },
    {
      id: 91,
      car: {
        photo: `${img}`,
        name: "프라임550",
        cost: "68,000,000",
        type: "포터",
        license: "2종 보통",
        people: "5인",
        date: "22년 03월",
        company: "드림캠핑카",
        location: "경상권",
      },
    },
    {
      id: 92,
      car: {
        photo: `${img}`,
        name: "하모니B",
        cost: "62,000,000",
        type: "르노마스터",
        license: "1종 보통",
        people: "3인",
        date: "22년 03월",
        company: "드림캠핑카",
        location: "경상권",
      },
    },
    {
      id: 93,
      car: {
        photo: `${img}`,
        name: "하모니C",
        cost: "58,300,000",
        type: "르노마스터",
        license: "1종 보통",
        people: "3인",
        date: "22년 03월",
        company: "드림캠핑카",
        location: "경상권",
      },
    },
    {
      id: 95,
      car: {
        photo: `${img}`,
        name: "V630J",
        cost: "121,000,000",
        type: "피아트 듀카토",
        license: "1종 보통",
        people: "4인",
        date: "22년 03월",
        company: "모터홈코리아",
        location: "수도권",
      },
    },
    {
      id: 96,
      car: {
        photo: `${img}`,
        name: "P746GJ",
        cost: "139,000,000",
        type: "피아트 듀카토",
        license: "1종 보통",
        people: "5인",
        date: "22년 03월",
        company: "모터홈코리아",
        location: "수도권",
      },
    },
  ],
};
